# Generated by Django 3.0.6 on 2020-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('base62_id', models.CharField(max_length=7)),
            ],
        ),
    ]
