# Generated by Django 3.0.6 on 2020-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200512_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='base62_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
